### ISSUE TITLE
UNKNOWN IO ERROR during download on some devices

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#204]
Zapp-Version: 3.5.0

Android-Version: 10

Devices:
- Oneplus

Could be related to timeout settings in Fetch.

**Comment by alexanderadam** [comment]
I guess it's better to answer [your question (_which version of Android are you using?_)](https://github.com/mediathekview/zapp/issues/117#issuecomment-685675512) here:

I'm using Android 10 on all of my devices (Samsung S9 and Samsung Galaxy Tab S6).

**Comment by cemrich** [comment]
> I'm also curious why it's not causing some kind of timeout error but an unknown error instead
Yes, that is interesting. I think this might be an Android 10 issue because on user reported this error on Android 10 but not on Android 9 using the same wifi network.

I will try to reproduce it and maybe come back to you.

**Comment by cemrich** [comment]
Curious. I can't even start a download of this show on my device.

**Comment by cemrich** [comment]
- Android 10, fresh app install, large file: download gets queued but never proceeds (update: proceeds very, very slow)
- Android 10, fresh app install, small file: download runs just fine
- Android 7, fresh app install, large file: download runs just fine
- Android 7, fresh app install, small file: download runs just fine

I think I narrowed this error down to large file sizes on Android 10 devices. Maybe this is a fetch problem of some kind?

**Comment by cemrich** [comment]
It is not related with the MediaStore framework.

**Comment by cemrich** [comment]
The sd card is causing this issue.

@alexanderadam I don't know if you have enough storage space left on your device; But does the same error occur if you do not download to sd card but to internal storage? On my device I cannot download any large file to sd card. It does not even show a notification. Downloading to internal storage seems to work fine. Can you verify this?

**Comment by alexanderadam** [comment]
Interesting thought, Sherlock! :female_detective: 

I cannot check the file size at the moment but it could be the 4 GB limit of FAT32 filesystem that appears here.
I cannot check this at the moment but I'm coming back on you once I checked it.

**Comment by cemrich** [comment]
> The 4 GB-bug of FAT32 cannot be the cause in this case though
No, the files I tested were much smaller.

> sorry, this issue also happens on internal space in my case
Do you think it is the same issue? I wonder, if we are debugging two different issues here.

> If this command is much faster for you, you obvious are simply getting a faster delivery than me
It averages around 1.5MB/s but is changing very fast.

I think I can improve timeouts, set another downloader for Fetch to use and release a new beta. This does not fix my sd card issue but maybe your timeout / io error...

**Comment by alexanderadam** [comment]
> Do you think it is the same issue? I wonder, if we are debugging two different issues here.

I have the feeling that `UNKNOWN_IO_ERROR` is simply not a very speaking error class. It could probably be any unhandled error.

> I think I can improve timeouts, set another downloader for Fetch to use and release a new beta. 

Sounds good. I will give you feedback again, after I was able to test it.

**Comment by cemrich** [comment]
> Is this comment helping in any way?

Yes, I enabled logging, but nothing helpful there. I tweaked the parameters quite a bit.  It *has* to be better now ;)

> I just found something regarding this (other) issue:

Did you ever see a FILE_ALLOCATION_FAILED error?

**Comment by alexanderadam** [comment]
> Did you ever see a FILE_ALLOCATION_FAILED error?

No, I need a file bigger than 4 GB to provoke that issue and I don't know any video with that size (yet).

**Comment by cemrich** [comment]
The beta version will have to wait a bit. OkHTTP causes other issues (like errors are not recognized correctly). I will have to test different options before releasing anything.

**Comment by alexanderadam** [comment]
I know that I wrote this before already but I _really_ hope that you _know_ that people value the work you're doing. Thank you so much for doing this.

**Comment by cemrich** [comment]
I just released [3.5.1-beta.1](https://github.com/mediathekview/zapp/releases/tag/3.5.1-beta.1) with increased timeouts and OkHTTP downloader. Additionally files are no longer pre allocated which fixes my sd card problem. Please give it a try and report any errors!

**Comment by ybrhue** [comment]
Sadly doesn't fix the issue for me.
Can't download neither internal need r external, switched back to 3.4.

Thanks a lot tough for your awesome work!
Android 10 on a rooted redmi note 8 pro (xiaomi).

**Comment by alexanderadam** [comment]
I can confirm that this exact bug is still present.

**Comment by cemrich** [comment]
@ybrhue Do you see a `UNKNOWN_IO_ERROR` inside the error notification? Does the download fail immediately or after some download progress? Does it occur only for larger files or for smaller ones too?

**Comment by cemrich** [comment]
I just published another release [3.5.1-beta.2](https://github.com/mediathekview/zapp/releases/tag/3.5.1-beta.2) to further test this issue. There is now a small "Report"-Button inside the download error notification which will give you the opportunity to send me a detailed error report.

Feel free to add further information to the mail or to paste the error stacktrace right here into this issue.

Thanks for your help!

**Comment by alexanderadam** [comment]
> Does the download fail immediately or after some download progress? Does it occur only for larger files or for smaller ones too?

After some download progress and only on larger files.

**Comment by cemrich** [comment]
> I don't have an error notification in this release and I can't see a Report button.

@alexanderadam There should be one. Can you please confirm there is no notification by killing the connection during download?
This bug is getting weirder and weirder...

**Comment by alexanderadam** [comment]
Sorry, my fault. I had swipe the notification down again to see the sharing thingy and this wasn't really obvious to me at first.

It seems that this will only open the email program with your email address as receiver, howevery. It is not attaching a backtrace or any other info.

**Comment by cemrich** [comment]
> However, it seems that this will only open the email program with your email address as receiver. It is not attaching a backtrace or any other info, though.

There should be a bunch of text inside the mail. I confirmed it works at least with K9 mail, but this should be pretty standard with all other mail apps. Maybe you mail app cannot process the intent used by ACRA crash reporting...

**Comment by cemrich** [comment]
I got the same error message from a few people using Android 10 devices downloading to internal memory:

```
java.io.IOException: write failed: EBADF (Bad file descriptor)
        at libcore.io.IoBridge.write(IoBridge.java:544)
        at java.io.FileOutputStream.write(FileOutputStream.java:392)
        at com.tonyodev.fetch2core.x$a.g(StorageResolverHelper.kt:1)
        at com.tonyodev.fetch2.v.f.k(SequentialFileDownloaderImpl.kt:7)
        at com.tonyodev.fetch2.v.f.run(SequentialFileDownloaderImpl.kt:46)
        at com.tonyodev.fetch2.v.c$a.run(DownloadManagerImpl.kt:10)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        Caused by: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
        at libcore.io.Linux.writeBytes(Native Method)
        at libcore.io.Linux.write(Linux.java:294)
        at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
        at libcore.io.BlockGuardOs.write(BlockGuardOs.java:416)
        at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
        at libcore.io.IoBridge.write(IoBridge.java:539)
```

I got the error on my test device but I have no clue on how to reproduce it...

**Comment by cemrich** [comment]
The error may be related to https://github.com/tonyofrancis/Fetch/issues/454

**Comment by cemrich** [comment]
A new version 3.6.0 is out and will hit F-Droid in a couple of days. Can you please test if downloading behaves differently now? I may have fixed the error but I am not really sure...

**Comment by alexanderadam** [comment]
I will test it. I hope I won't miss the release (you can remind me in case I forget it).

**Comment by cemrich** [comment]
@alexanderadam It is released!

**Comment by alexanderadam** [comment]
@cemrich seems to work perfectly! :tada: 

Just a small question: in case a download can't be finished there's still the half downloaded video file around somewhere, right?
Can this be deleted as well? I cannot test it anymore since the downloads are working fine now :wink: 

I guess this issue can be closed then?

**Comment by cemrich** [comment]
> seems to work perfectly! 🎉

Yay! Finally! 

> Just a small question: in case a download can't be finished there's still the half downloaded video file around somewhere, right?
Can this be deleted as well?

No, they don't get deleted, but maybe should... I created issue #212
Cancelling a download however does delete it.
